name: Backstop Sanity Tests

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: write
  contents: write
  pull-requests: write

env:
  NODE_VERSION: 20

jobs:
  sanity-puppeteer:
    name: ğŸ¤ª Puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: â¬¢ Setup Node & Cache
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: â†§ Install
        run: npm ci

      - name: "ğ“‹ Run `npm run sanity-test`"
        continue-on-error: true
        run: |
          npm run sanity-test

      - name: "Validate Puppeteer Test Results"
        run: |
          diff -c <(jq 'walk(if type == "object" then with_entries(.value |= if type == "object" or type == "array" then . else "" end) else . end) | del(.tests[].pair.diff)' test/__fixtures__/sanity-test.json) \
            <(jq 'walk(if type == "object" then with_entries(.value |= if type == "object" or type == "array" then . else "" end) else . end) | del(.tests[].pair.diff)' test/configs/backstop_data/bitmaps_test/**/report.json)
          RESULT=$?
          if [[ $RESULT == "0" ]]; then
            echo "# âœ… Puppeteer Sanity Test Valid" >> $GITHUB_STEP_SUMMARY
            echo "```diff\n${RESULT}\n```" >> $GITHUB_STEP_SUMMARY \
            && exit 0
          else
            echo "# â Puppeteer Sanity Validation Diff" >> $GITHUB_STEP_SUMMARY
            echo "```diff\n${RESULT}\n```" >> $GITHUB_STEP_SUMMARY \
            && exit 1
          fi

  sanity-playwright:
    name: ğŸ¤ª Playwright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: â¬¢ Setup Node & Cache
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: â†§ Install
        run: npm ci

      - name: "ğŸ­ Run `npm run sanity-test-playwright`"
        continue-on-error: true
        run: |
          npx playwright install --with-deps
          npm run sanity-test-playwright

      - name: "Validate Playwright Test Results"
        run: |
          diff -c <(jq 'walk(if type == "object" then with_entries(.value |= if type == "object" or type == "array" then . else "" end) else . end) | del(.tests[].pair.diff)' test/__fixtures__/sanity-test-playwright.json) \
            <(jq 'walk(if type == "object" then with_entries(.value |= if type == "object" or type == "array" then . else "" end) else . end) | del(.tests[].pair.diff)' test/configs/backstop_data/bitmaps_test/**/report.json)
          RESULT=$?
          if [[ $RESULT == "0" ]]; then
            echo "# âœ… Playwright Sanity Test Valid" >> $GITHUB_STEP_SUMMARY
            echo "```diff\n${RESULT}\n```" >> $GITHUB_STEP_SUMMARY \
            && exit 0
          else
            echo "# â Playwright Sanity Validation Diff" >> $GITHUB_STEP_SUMMARY
            echo "```diff\n${RESULT}\n```" >> $GITHUB_STEP_SUMMARY \
            && exit 1
          fi
